decentraland/explorer-desktop

- README.md
- update-unity-renderer.sh
Fix decentraland/unity-renderer#1231
Use the script
```
./update-unity-renderer.sh ../unity-renderer
```
> chore: update-unity-renderer script now accept local path as argument

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/DisplaySettings.cs
- unity-renderer-desktop/Packages/packages-lock.json
> fix: compile error

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
The application will close if the WebSocket connection is closed, this was removed because we needed to close the connection in order for a restart to work. Now, this functionality is back and is compatible with the restart functionality.
Close the client and the application should close.
Restart the client if there is a timeout and the application shouldn't close.
> fix: `explorer-desktop` not closing when the `kernel communication` is closed

- .circleci/config.yml
This fixed the issues with the `playmode-tests` that were failing because of missing .meta files.
> chore: download UPM unity renderer locally to be able to generate the needed .meta files

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Preloading/Preloading.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Preloading/PreloadingController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.asmdef
- unity-renderer-desktop/Packages/packages-lock.json
> chore: update version and fix compatibility issues

- unity-renderer-desktop/Packages/packages-lock.json
- unity-renderer-desktop/ProjectSettings/ProjectSettings.asset
Removes the unity splash screen that was added by mistake
> chore: remove unity splash screen

- unity-renderer-desktop/Assets/Scenes/MainScene.unity
- unity-renderer-desktop/Packages/packages-lock.json
- unity-renderer-desktop/ProjectSettings/ProjectSettings.asset
Changed application window name to `Decentraland`
Updated `unity-renderer` version
Fixes https://github.com/decentraland/unity-renderer/issues/1635
> chore: change window name

- unity-renderer-desktop/Packages/packages-lock.json
> chore: updated unity renderer

- unity-renderer-desktop/Assets/Scenes/MainScene.unity
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDControllerDesktop.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop.prefab
Fixes https://github.com/decentraland/unity-renderer/issues/1674
> fix: exit button now appears on guest mode and has a new design

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop.prefab
- unity-renderer-desktop/Packages/packages-lock.git.json
- unity-renderer-desktop/Packages/packages-lock.json
Updated exit button art style.
> chore: update exit button art

- .github/workflows/main.yml
> chore: add custom protocol to the github PR comment

- .github/ISSUE_TEMPLATE/bug_report.yml
> docs: report bug template

- update-unity-renderer.sh
Following #84, this PR makes the updater-script format into a human-readable format.
> chore: `unity renderer updater` now writes JSON into a human-readable format

- unity-renderer-desktop/Assets/Scenes/MainScene.unity
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
> chore: enable multithreading by default

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop.prefab
Enabled logout button in ProfileHUDDesktop
> chore: enable logout button

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop.prefab
Renamed logout button to signout and updated positions
> chore: update sign-out button text and position

- unity-renderer-desktop/Packages/packages-lock.json
> chore: update version

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUDDesktop.prefab
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop.prefab
- Decentraland “beta” label is deformed.
- Background of  Decentraland logo under the minimap is too transparent.
- Log out and Exit button hover is not visible.
> fix: UIMiniFixes

- unity-renderer-desktop/ProjectSettings/QualitySettings.asset
Fixes https://github.com/decentraland/explorer-desktop/issues/119
Go to genesis plaza, the water should reflect the sky in real-time.
> fix: skybox reflections

- unity-renderer-desktop/Packages/packages-lock.json
This reverts commit 1779adddf14c4267e79abb3385fb6cc91b535553.
> revert: "chore: update version (#165)"

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemFactoryDesktop.cs
- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> chore: update version (branch rerevert/gltf-multithreading)

- unity-renderer-desktop/Packages/packages-lock.json
Fix deadlock and eof to avoid log spam
> chore: update DCLVideoPlayerUnity version

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemFactoryDesktop.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Fixes #116 
Press the exit button, the client shouldn't crash.
> fix: crash on exit

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
Small performance improvement. ( #191 )
> chore: added flag to allow threaded texture creation

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/ResolutionSizeControlController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/WindowModeControlController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/SettingsPanelHUDDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/DisplaySettings.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
Merge dev into master, see Commits for changelog
> Release Candidate

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LogReport.meta
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LogReport/LogReportKernelInterface.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LogReport/LogReportKernelInterface.cs.meta
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LogReport/LogReportPlugin.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LogReport/LogReportPlugin.asmdef.meta
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LogReport/LogReportPlugin.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LogReport/LogReportPlugin.cs.meta
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemFactoryDesktop.cs
Fix: decentraland/explorer-desktop#173
> feat: report rollout

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowView.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/Resources/LoadingFlow.prefab
Changes the timeout error based on #216 
> chore: change timeout error to a more descriptive one

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Components/ComponentsDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoComponentDesktopTests.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemFactoryDesktop.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/Tests/MainDesktopShould.cs
Make explorer-desktop compatibility with https://github.com/decentraland/unity-renderer/pull/2083
> refactor: plugin system compatibility for explorer-desktop

- .github/workflows/debug.yml
...
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> chore: create debug.yml

- .github/workflows/deploy-release.yml
> chore: fix repo name in gh

- unity-renderer-desktop/Packages/packages-lock.json
> chore: update video player version

- unity-renderer-desktop/Packages/packages-lock.json
Updates unity-renderer to the last version
> chore: update unity-renderer for release

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
This is an urgent release that points to [this branch](https://github.com/decentraland/unity-renderer/pull/2580) 
> chore: release for kernel

- unity-renderer-desktop/Packages/packages-lock.json
Updates the latest changes of unity-renderer dependency
> release: 20220714

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Release Candidate Testing Spreadsheet: https://docs.google.com/spreadsheets/d/1xagjgvjHX1vO-tXv9WW32iNbCRSOxMAZlif1wdhnY3E/edit#gid=2073364387
> Release 2022-08-03

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Closes [#2819](https://github.com/decentraland/unity-renderer/issues/2819)
> Release 2022-08-09

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Release Candidate Testing Spreadsheet: https://docs.google.com/spreadsheets/d/1xagjgvjHX1vO-tXv9WW32iNbCRSOxMAZlif1wdhnY3E/edit#gid=2073364387
> Release 2022-08-18

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Mini hotfix release needed for the art week
> Release 2022-08-25

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> Release 2022 09 01

- unity-renderer-desktop/Packages/packages-lock.json
This reverts commit 9c901c938ed4cfef7fd1257233afcb0ac10bfb8e.
> release: Revert "Release 2022-09-01 (#377)"

- unity-renderer-desktop/Packages/packages-lock.json
> Hotfix Release 2022-09-12

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/ConfigurationDesktop/ConfigurationDesktop.cs
A couple of values missing in the new texture settings
Closes #324
> chore: texture compression settings missing increase

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Release branch
Check the RC document
> Release 2022-09-15

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Release candidate
See the RC spreadsheet
> Release 2022-09-27

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
- unity-renderer-desktop/ProjectSettings/TagManager.asset
**Release Candidate Testing Spreadsheet**: https://docs.google.com/spreadsheets/d/1xagjgvjHX1vO-tXv9WW32iNbCRSOxMAZlif1wdhnY3E/edit#gid=512199622
**Test link**:
- Normal mode: https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=release/release-20221006
- Developer mode: https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=release/release-20221006&DESKTOP-DEVELOPER-MODE
> Release 2022-10-06

- unity-renderer-desktop/ProjectSettings/InputManager.asset
This PR is needed to fix #3123 which is related to same input issue we fixed in the web client previously (character autorun).
Closes #3123
Test if the character runs without any issues.
> fix: disable joystick input using same approach as for web client

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> release: update pacakge to renderer release 2022 10 24

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Includes the implementation of channels feature.
https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=release/release-20221025&ENABLE_MATRIX_CHANNELS_ENABLED
> release: 2022-10-25

- unity-renderer-desktop/Packages/packages-lock.json
Hotfix for desktop to put experiences panel above notifications panel
> Hotfix 2022-11-28

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> release: 2022-11-09

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Fixes a problem with multithreading and objects with too many animations
> Release 2022-11-10

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> release: 20221115

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDDesktopFactory.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDControllerDesktop.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDDesktop.asmdef
- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> release: 2022-11-24

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDControllerDesktop.cs
Special merge without logic change, to re-run CI (since we get problems with the commit not showing up in the rollout query)
> release: merge to re-run CI

- unity-renderer-desktop/Packages/packages-lock.json
> hotfix: updated renderer to f11d4da24ee9f1ced096a7bb4d992249596e4457

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.git.json
- unity-renderer-desktop/Packages/packages-lock.json
- unity-renderer-desktop/ProjectSettings/BurstAotSettings_StandaloneWindows.json
- unity-renderer-desktop/ProjectSettings/BurstAotSettings_WebGL.json
- unity-renderer-desktop/ProjectSettings/CommonBurstAotSettings.json
- unity-renderer-desktop/ProjectSettings/PackageManagerSettings.asset
- unity-renderer-desktop/ProjectSettings/ProjectSettings.asset
Release candidate
Check the test [spreadsheet](https://docs.google.com/spreadsheets/d/1xagjgvjHX1vO-tXv9WW32iNbCRSOxMAZlif1wdhnY3E/edit#gid=1196993110)
> Release: Release 2022-12-07

- unity-renderer-desktop/Packages/packages-lock.json
> hotfix: other avatar's emote not playing (#3709)

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> hotfix: hotfix 2022 12 19

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> release: 20221220

- ci-build.sh
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDControllerDesktop.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDViewDesktop.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop.prefab
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop.prefab.meta
- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Release candidate
Check the testing sheet
> Release 20221228

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Release candidate
Check the testing sheet
> Release 2023-01-03

- .github/workflows/set-rollout-manual.yml
- .github/workflows/set-rollout.yml
> upgrade ubuntu runner

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
- unity-renderer-desktop/ProjectSettings/TagManager.asset
https://docs.google.com/spreadsheets/d/1xagjgvjHX1vO-tXv9WW32iNbCRSOxMAZlif1wdhnY3E/edit#gid=333071376
https://docs.google.com/spreadsheets/d/1qqseVUBMYp63xcadSXsTz_caRFQ4VOcBV1Evqa3EfKQ/edit#gid=802671791
https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=release/release-20220111&ENABLE_AVATAR_OUTLINER&ENABLE_NEW_FRIEND_REQUESTS&ENABLE_NEW_AVATAR_FLOW
> Release 2023-01-11

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
> Release 2023 01 25

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Point to the last renderer's main commit
> hotfix: Point to the last renderer's main commit
