decentraland/explorer-desktop

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/Tests/PlayerPrefsDesktopDisplaySettingsRepositoryShould.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/Tests/PlayerPrefsDesktopDisplaySettingsRepositoryShould.cs.meta
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/Tests/SettingsDesktopTests.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/Tests/SettingsDesktopTests.asmdef.meta
In #33 I deleted tests to unblock the Desktop Pipeline because we had some problems with `NSubstitute`.
In this PR we're re-adding the test.
> chore: add setting test

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/VSyncControlController.cs
Hard caps FPS to 240 when v-sync is disabled to avoid melting fast GPUs
Fixes https://github.com/decentraland/unity-renderer/issues/1507
Fixes https://github.com/decentraland/unity-renderer/issues/478
> chore: fps hardcap

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
Shows the timeout popup during loading screen when any fatal error ocurred on renderer while loading assets.
1. Start DCL many times
2. The loading should never freeze at 99%
> fix: fatal error freeze

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Resources/SettingsPanelHUDDesktop.prefab
Fixed Desktop settings not showing up
> fix: desktop-only settings not showing up

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
Adds a try-catch to `MainDesktop.OnDestroy()` to prevent crashes and bug splats on exiting the application.
> fix: exceptions on exit

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/Resources/LoadingFlow.prefab
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
Added a 15 seconds timeout for web socket connection during the loading process. The timeout will trigger the loading error popup.
There is not an easy to test this, since its something that happens sometimes. You can follow the steps forcing the error:
1. Go to class `DCLWebSocketService`
2. Comment the method `OnOpen()`
3. Start the loading flow
4. After 15 seconds a timeout popup should appear
> fix: loading flow also considers web socket connection timeout

- README.md
Fixes a wrong URL redirect in the README file (https://github.com/decentraland/explorer -> https://github.com/decentraland/kernel)
...
NA
> Fixing wrong URL in README.md

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.json
Fixes a random crash caused by FFMPEG decoder by disabling the plugin temporaly
Also fixed Unity forced SSL and port
> fix: disabled FFMPEG video decoder plugin that was causing crashes

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Configs/ToggleSettingsControlTemplateDesktop.prefab
Fixes the color of v-sync toggle's background to be the same as the rest.
1. Open the settings panel (press TAB)
2. Set window mode to full screen
3. Click the vsync toggle
4. Check that the background color is correct
> fix: vsync toggle color

- unity-renderer-desktop/Packages/packages-lock.json
Includes the unity-renderer commit that fixes the gif overlapping issue
> fix: gif nftshapes preview modal breaks subsequent preview modals

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/VSyncControlController.cs
- unity-renderer-desktop/Packages/packages-lock.json
Removed target framerate override to fix FPSCap in unity-renderer side, the max FPS requested (240) will be applied in the unity-side PR (https://github.com/decentraland/unity-renderer/pull/1983).
We should wait until we merged https://github.com/decentraland/unity-renderer/pull/1983 and updated the unity-renderer consumed package version before merging this PR
> chore: remove targetframerate override to fix fps cap

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
bound minimum resolution to half of max resolution detected.
Hopefully this will solve the issue tracked at https://github.com/decentraland/explorer-desktop/issues/121
> fix: portrait minimum resolution

- unity-renderer-desktop/Packages/packages-lock.json
Updated commit consumed from unity-renderer to last one before 67d2a2a5a1891a18f0a44304f754103f37bd8c91 (feat: emotes catalog (#1992)) as that one introduces a problem loading the character in desktop
> chore: update version

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystemDesktop/PluginSystemFactoryDesktop.cs
- unity-renderer-desktop/Packages/packages-lock.json
Emote animations plugins was not implemented here and therefore throwing errors.
In any case gonna add some validation in the main renderer so the plugin it can actually be removed without breaking anything.
> chore: emoteAnimations plugin is now implemented.

- unity-renderer-desktop/Packages/packages-lock.json
Fix Desktop crash with the VideoPlayer when you execute `GetDuration()` of a Media which don't have a Video.
> chore: update DCLVideoPlayerUnity version

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/ResolutionSizeControlController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/WindowModeControlController.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/SettingsPanelHUDDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/DisplaySettings.cs
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.asmdef
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
Changed how we handle the initial and startup resolution by just using the one on player prefs, this one defaults as borderless max resolution if not available. (#121)
Added a shortcut ( `CTRL+F11`) to force max resolution and full screen to avoid small resolution issues where you can't get into settings because the UI is not scaling properly.
Also fixed a weird bug that happens when changing from windowed to borderless
Uninstall the launcher so the player-prefs are deleted, then reinstall and launch, application should have a full-screen max resolution setting by default.
Setup the smallest resolution available, close settings, and press `CTRL+F11` to go back to borderless max resolution
> fix: resolution workaround to avoid small resolutions on big displays

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/WindowModeControlController.cs
We know that unity doesn't like the resolution size being changed while you are switching from windowed/fullscreen so we are adding a new routine to wait for a frame and re-applying the screen size.
This is an effort to fix https://github.com/decentraland/explorer-desktop/issues/232
> fix: aspect ratio bug

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Configs/ScenesLoadRadiusControlConfigurationDesktop.asset
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Configs/ScenesLoadRadiusControlConfigurationDesktop.asset.meta
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Configs/SettingsPanelConfigurationDesktop.asset
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Sections/GeneralSectionDesktop.asset
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Sections/GeneralSectionDesktop.asset.meta
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Widgets/GeneralWidgetDesktop.asset
- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Widgets/GeneralWidgetDesktop.asset.meta
I had to override the settings scriptable objects to allow us to change the load radius easily.
Required for https://github.com/decentraland/unity-renderer/issues/2220
Enter settings (P) max scene load radius should be 4 for now.
> chore: set max load radius to 4

- unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoComponenteDesktopShould.cs
Remove unused prefabs and references.
> fix: Remove unused prefabs and references (Desktop side)

- unity-renderer-desktop/Packages/manifest.json
- unity-renderer-desktop/Packages/packages-lock.git.json
- unity-renderer-desktop/Packages/packages-lock.json
Add a dependency to webgl-ime to avoid "missing" scripts warnings.
> chore: add webgl-ime-input to packages
